import asyncio
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from src.domain.value_object.employment_type import EmploymentType
from src.domain.value_object.ids import EmployerId, VacancyId
from src.domain.value_object.workformat import WorkFormat
from src.infra.adapters.database.models import Base, EmployerModel, VacancyModel

mock_employers = [
    {
        "id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
        "name": "УрФУ",
        "avatar_url": "https://img.phb123.com/uploads/allimg/220614/810-220614113K60-L-lp.png",
        "description": """Уральский федеральный университет является крупнейшим вузом Урала, ведущим научно-образовательным центром региона и одним из крупнейших вузов Российской Федерации.
В 2023 году университет занял 3 место в Рейтинге крупнейших университетов России и 12 место в России по количеству иностранных студентов, по данным Мониторинга Министерства науки и высшего образования РФ в университете в 2023 году обучались 38 797 и 3 376 чел соответственно.
Учебный процесс обеспечивают 3782 преподавателя, среди них более 560 докторов наук и около 1900 кандидатов наук, более 30 членов государственных академий. Вуз проводит обучение по 102 направлениям бакалавриата, 90 направлениям магистратуры, 126 специальностям аспирантуры и 42 специальностям докторантуры. В университете функционирует более 30 диссертационных советов""",
    },
    {
        "id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
        "name": "ВШЭ СПБ",
        "avatar_url": "https://papik.pro/grafic/uploads/posts/2023-04/1681593331_papik-pro-p-niu-vshe-logotip-vektor-6.jpg",
        "description": "Национа́льный иссле́довательский университе́т «Вы́сшая шко́ла эконо́мики» (НИУ ВШЭ; разг. «Вы́шка») — автономное учреждение, федеральное государственное высшее учебное заведение. ВШЭ создана в 1992 году, нынешний статус носит с 2009 года. Основной кампус находится в Москве, ещё три — в Санкт-Петербурге, Нижнем Новгороде и Перми. Также имеется онлайн кампус для образовательных программ, проводимых онлайн.",
    },
]

mock_vacancies = [
    {
        "id": VacancyId(UUID("01960c29-20de-71a1-a4e7-509120b6527f")),
        "title": "Ассистент преподавателя",
        "location": "Екатеринбург",
        "salary_from": 20000,
        "salary_to": 30000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.PART_TIME,
        "description": "Описание вакансии для ассистент преподавателя в Екатеринбург.",
        "key_skills": ["Python", "Преподавание", "Работа с документацией"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-8f45-771d-a8d6-2a9b1ca9a86d")),
        "title": "Административный помощник",
        "location": "Санкт-Петербург",
        "salary_from": 25000,
        "salary_to": 35000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для административный помощник в Санкт-Петербург.",
        "key_skills": ["Коммуникации", "Организация мероприятий"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-c88c-7104-969f-566213debd7f")),
        "title": "Стажёр в ИТ-отдел",
        "location": "Екатеринбург",
        "salary_from": 15000,
        "salary_to": 20000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.INTERNSHIP,
        "description": "Описание вакансии для стажёр в ИТ-отдел в Екатеринбург.",
        "key_skills": ["Техническая поддержка", "Windows", "Linux"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-dfd4-7433-9a41-d86f152cb50f")),
        "title": "Исследователь-стажёр",
        "location": "Санкт-Петербург",
        "salary_from": 10000,
        "salary_to": 15000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.INTERNSHIP,
        "description": "Описание вакансии для исследователь-стажёр в Санкт-Петербург.",
        "key_skills": ["Статистика", "Python", "R"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-1a2b-11e5-bb77-1234567890c4")),
        "title": "Куратор учебных программ",
        "location": "Екатеринбург",
        "salary_from": 30000,
        "salary_to": 40000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для куратор учебных программ в Екатеринбург.",
        "key_skills": ["Организаторские способности", "Документооборот", "Кураторство"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-2b3c-11e5-bb77-1234567890c5")),
        "title": "Менеджер по студенческим проектам",
        "location": "Санкт-Петербург",
        "salary_from": 32000,
        "salary_to": 42000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для менеджер по студенческим проектам в Санкт-Петербург.",
        "key_skills": [
            "Ивент-менеджмент",
            "Командная работа",
            "Проектная деятельность",
        ],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-3c4d-11e5-bb77-1234567890c6")),
        "title": "Ассистент по исследовательским проектам",
        "location": "Екатеринбург",
        "salary_from": 25000,
        "salary_to": 35000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.PART_TIME,
        "description": "Описание вакансии для ассистент по исследовательским проектам в Екатеринбург.",
        "key_skills": ["Аналитика", "Python", "Исследовательская деятельность"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-4d5e-11e5-bb77-1234567890c7")),
        "title": "Секретарь учебного отдела",
        "location": "Санкт-Петербург",
        "salary_from": 27000,
        "salary_to": 37000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для секретарь учебного отдела в Санкт-Петербург.",
        "key_skills": ["Работа с документами", "Внимательность", "1С Университет"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-5e6f-11e5-bb77-1234567890c8")),
        "title": "Технический ассистент кафедры",
        "location": "Екатеринбург",
        "salary_from": 24000,
        "salary_to": 32000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.PART_TIME,
        "description": "Описание вакансии для технический ассистент кафедры в Екатеринбург.",
        "key_skills": [
            "Техническая поддержка",
            "Ответственность",
            "Работа с оборудованием",
        ],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-6f80-11e5-bb77-1234567890c9")),
        "title": "Лаборант кафедры информатики",
        "location": "Екатеринбург",
        "salary_from": 18000,
        "salary_to": 25000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.PART_TIME,
        "description": "Описание вакансии для лаборант кафедры информатики в Екатеринбург.",
        "key_skills": ["Поддержка ПК", "Оргтехника", "Администрирование"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-8091-11e5-bb77-1234567890ca")),
        "title": "Координатор онлайн-курсов",
        "location": "Санкт-Петербург",
        "salary_from": 35000,
        "salary_to": 45000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для координатор онлайн-курсов в Санкт-Петербург.",
        "key_skills": ["LMS", "Электронное обучение", "Методическая поддержка"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-91a2-11e5-bb77-1234567890cb")),
        "title": "Ассистент бухгалтера",
        "location": "Екатеринбург",
        "salary_from": 22000,
        "salary_to": 30000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.PART_TIME,
        "description": "Описание вакансии для ассистент бухгалтера в Екатеринбург.",
        "key_skills": ["1С Бухгалтерия", "Документооборот", "Ведение отчетности"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-a2b3-11e5-bb77-1234567890cc")),
        "title": "Менеджер по международным связям",
        "location": "Санкт-Петербург",
        "salary_from": 40000,
        "salary_to": 50000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для менеджер по международным связям в Санкт-Петербург.",
        "key_skills": [
            "Английский язык",
            "Межкультурная коммуникация",
            "Организация визитов",
        ],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-b3c4-11e5-bb77-1234567890cd")),
        "title": "Стажёр в отдел маркетинга",
        "location": "Екатеринбург",
        "salary_from": 15000,
        "salary_to": 20000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.INTERNSHIP,
        "description": "Описание вакансии для стажёр в отдел маркетинга в Екатеринбург.",
        "key_skills": ["SMM", "Копирайтинг", "Аналитика соцсетей"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-c4d5-11e5-bb77-1234567890ce")),
        "title": "Администратор образовательных программ",
        "location": "Санкт-Петербург",
        "salary_from": 38000,
        "salary_to": 48000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для администратор образовательных программ в Санкт-Петербург.",
        "key_skills": [
            "Организация учебного процесса",
            "Расписание",
            "Документооборот",
        ],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-d5e6-11e5-bb77-1234567890cf")),
        "title": "Технический писатель",
        "location": "Екатеринбург",
        "salary_from": 45000,
        "salary_to": 60000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для технический писатель в Екатеринбург.",
        "key_skills": ["Техническая документация", "Английский язык", "Графика"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-e6f7-11e5-bb77-1234567890d0")),
        "title": "Куратор студенческого общежития",
        "location": "Санкт-Петербург",
        "salary_from": 28000,
        "salary_to": 35000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для куратор студенческого общежития в Санкт-Петербург.",
        "key_skills": [
            "Работа с молодежью",
            "Конфликтология",
            "Организаторские способности",
        ],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-f708-11e5-bb77-1234567890d1")),
        "title": "Аналитик данных",
        "location": "Екатеринбург",
        "salary_from": 50000,
        "salary_to": 70000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для аналитик данных в Екатеринбург.",
        "key_skills": ["SQL", "Python", "Визуализация данных", "Статистика"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-0819-11e5-bb77-1234567890d2")),
        "title": "Специалист по работе с выпускниками",
        "location": "Санкт-Петербург",
        "salary_from": 42000,
        "salary_to": 52000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для специалист по работе с выпускниками в Санкт-Петербург.",
        "key_skills": ["Фандрайзинг", "Event-менеджмент", "Коммуникации"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-192a-11e5-bb77-1234567890d3")),
        "title": "Веб-разработчик",
        "location": "Екатеринбург",
        "salary_from": 60000,
        "salary_to": 90000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для веб-разработчик в Екатеринбург.",
        "key_skills": ["JavaScript", "React", "Node.js", "HTML/CSS"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-2a3b-11e5-bb77-1234567890d4")),
        "title": "Методист",
        "location": "Санкт-Петербург",
        "salary_from": 40000,
        "salary_to": 55000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для методист в Санкт-Петербург.",
        "key_skills": ["Разработка программ", "ФГОС", "Педагогика"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-3b4c-11e5-bb77-1234567890d5")),
        "title": "Системный администратор",
        "location": "Екатеринбург",
        "salary_from": 55000,
        "salary_to": 75000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для системный администратор в Екатеринбург.",
        "key_skills": ["Linux", "Windows Server", "Сети", "Кибербезопасность"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-4c5d-11e5-bb77-1234567890d6")),
        "title": "Библиотекарь",
        "location": "Санкт-Петербург",
        "salary_from": 25000,
        "salary_to": 35000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.PART_TIME,
        "description": "Описание вакансии для библиотекарь в Санкт-Петербург.",
        "key_skills": [
            "Каталогизация",
            "Работа с читателями",
            "Информационные системы",
        ],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-5d6e-11e5-bb77-1234567890d7")),
        "title": "Стажёр в научную лабораторию",
        "location": "Екатеринбург",
        "salary_from": 12000,
        "salary_to": 18000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.INTERNSHIP,
        "description": "Описание вакансии для стажёр в научную лабораторию в Екатеринбург.",
        "key_skills": ["Лабораторное оборудование", "Эксперименты", "Научный метод"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-6e7f-11e5-bb77-1234567890d8")),
        "title": "Переводчик",
        "location": "Санкт-Петербург",
        "salary_from": 35000,
        "salary_to": 50000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.PART_TIME,
        "description": "Описание вакансии для переводчик в Санкт-Петербург.",
        "key_skills": ["Английский язык", "Технический перевод", "Коммуникация"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-7f90-11e5-bb77-1234567890d9")),
        "title": "Дизайнер образовательных материалов",
        "location": "Екатеринбург",
        "salary_from": 45000,
        "salary_to": 60000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для дизайнер образовательных материалов в Екатеринбург.",
        "key_skills": ["Graphic Design", "Illustrator", "Photoshop", "Визуализация"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-90a1-11e5-bb77-1234567890da")),
        "title": "Психолог",
        "location": "Санкт-Петербург",
        "salary_from": 40000,
        "salary_to": 55000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для психолог в Санкт-Петербург.",
        "key_skills": ["Консультирование", "Психодиагностика", "Работа со студентами"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-a1b2-11e5-bb77-1234567890db")),
        "title": "Тестировщик ПО",
        "location": "Екатеринбург",
        "salary_from": 50000,
        "salary_to": 70000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для тестировщик ПО в Екатеринбург.",
        "key_skills": ["QA", "Тест-кейсы", "Автоматизированное тестирование", "JIRA"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-b2c3-11e5-bb77-1234567890dc")),
        "title": "Специалист по качеству образования",
        "location": "Санкт-Петербург",
        "salary_from": 45000,
        "salary_to": 60000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для специалист по качеству образования в Санкт-Петербург.",
        "key_skills": ["Мониторинг", "Аналитика", "Аккредитация", "Отчетность"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-c3d4-11e5-bb77-1234567890dd")),
        "title": "Контент-менеджер",
        "location": "Екатеринбург",
        "salary_from": 40000,
        "salary_to": 55000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.PART_TIME,
        "description": "Описание вакансии для контент-менеджер в Екатеринбург.",
        "key_skills": ["Копирайтинг", "SEO", "Работа с CMS", "Соцсети"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-d4e5-11e5-bb77-1234567890de")),
        "title": "Архивариус",
        "location": "Санкт-Петербург",
        "salary_from": 30000,
        "salary_to": 40000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для архивариус в Санкт-Петербург.",
        "key_skills": [
            "Деловодство",
            "Архивное дело",
            "Систематизация",
            "Внимательность",
        ],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-e5f6-11e5-bb77-1234567890df")),
        "title": "Разработчик мобильных приложений",
        "location": "Екатеринбург",
        "salary_from": 70000,
        "salary_to": 100000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для разработчик мобильных приложений в Екатеринбург.",
        "key_skills": ["Kotlin", "Swift", "Flutter", "REST API"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-f707-11e5-bb77-1234567890e0")),
        "title": "Специалист по трудоустройству",
        "location": "Санкт-Петербург",
        "salary_from": 42000,
        "salary_to": 52000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для специалист по трудоустройству в Санкт-Петербург.",
        "key_skills": ["Карьерное консультирование", "HR", "Работа с компаниями"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-0818-11e5-bb77-1234567890e1")),
        "title": "Сетевой администратор",
        "location": "Екатеринбург",
        "salary_from": 60000,
        "salary_to": 80000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для сетевой администратор в Екатеринбург.",
        "key_skills": ["Cisco", "TCP/IP", "Безопасность сетей", "Диагностика"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-1929-11e5-bb77-1234567890e2")),
        "title": "Редактор научных publications",
        "location": "Санкт-Петербург",
        "salary_from": 38000,
        "salary_to": 50000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.PART_TIME,
        "description": "Описание вакансии для редактор научных publications в Санкт-Петербург.",
        "key_skills": ["Академическое письмо", "Peer review", "Английский язык"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-2a3a-11e5-bb77-1234567890e3")),
        "title": "DevOps инженер",
        "location": "Екатеринбург",
        "salary_from": 80000,
        "salary_to": 120000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для devops инженер в Екатеринбург.",
        "key_skills": ["Docker", "Kubernetes", "CI/CD", "AWS"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-3b4b-11e5-bb77-1234567890e4")),
        "title": "Координатор волонтерских программ",
        "location": "Санкт-Петербург",
        "salary_from": 32000,
        "salary_to": 42000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для координатор волонтерских программ в Санкт-Петербург.",
        "key_skills": ["Управление проектами", "Мотивация", "Социальная работа"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-4c5c-11e5-bb77-1234567890e5")),
        "title": "Специалист по кибербезопасности",
        "location": "Екатеринбург",
        "salary_from": 90000,
        "salary_to": 130000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для специалист по кибербезопасности в Екатеринбург.",
        "key_skills": ["Penetration testing", "SOC", "Forensics", "SIEM"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-5d6d-11e5-bb77-1234567890e6")),
        "title": "Организатор студенческих мероприятий",
        "location": "Санкт-Петербург",
        "salary_from": 30000,
        "salary_to": 40000,
        "work_format": WorkFormat.ONSITE,
        "employment_type": EmploymentType.PART_TIME,
        "description": "Описание вакансии для организатор студенческих мероприятий в Санкт-Петербург.",
        "key_skills": ["Креативность", "Логистика", "Тимбилдинг", "Ивент-менеджмент"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-6e7e-11e5-bb77-1234567890e7")),
        "title": "Data scientist",
        "location": "Екатеринбург",
        "salary_from": 100000,
        "salary_to": 150000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для data scientist в Екатеринбург.",
        "key_skills": [
            "Machine Learning",
            "Python",
            "Big Data",
            "Статистическое моделирование",
        ],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
    {
        "id": VacancyId(UUID("01960c29-7f8f-11e5-bb77-1234567890e8")),
        "title": "Куратор дистанционного обучения",
        "location": "Санкт-Петербург",
        "salary_from": 45000,
        "salary_to": 58000,
        "work_format": WorkFormat.REMOTE,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для куратор дистанционного обучения в Санкт-Петербург.",
        "key_skills": ["Moodle", "Техподдержка", "Методическое сопровождение"],
        "employer_id": EmployerId(UUID("01960c2a-9938-74ff-8fe1-027402ef0b9b")),
    },
    {
        "id": VacancyId(UUID("01960c29-90a0-11e5-bb77-1234567890e9")),
        "title": "Frontend-разработчик",
        "location": "Екатеринбург",
        "salary_from": 80000,
        "salary_to": 110000,
        "work_format": WorkFormat.HYBRID,
        "employment_type": EmploymentType.FULL_TIME,
        "description": "Описание вакансии для frontend-разработчик в Екатеринбург.",
        "key_skills": ["Vue.js", "TypeScript", "Webpack", "UI/UX"],
        "employer_id": EmployerId(UUID("01960c2a-5ad1-7651-80bf-54760bd9d55a")),
    },
]


async def seed():
    engine = create_async_engine(
        "sqlite+aiosqlite:////home/hirotasoshu/code/unijobs-backend/test.db",
        echo=True,
    )
    async_session = sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        # Employers
        for e in mock_employers:
            session.add(
                EmployerModel(
                    id=e["id"],
                    name=e["name"],
                    avatar_url=e["avatar_url"],
                    description=e["description"],
                )
            )

        # Vacancies
        for v in mock_vacancies:
            session.add(
                VacancyModel(
                    id=v["id"],
                    title=v["title"],
                    location=v["location"],
                    salary_from=v["salary_from"],
                    salary_to=v["salary_to"],
                    work_format=v["work_format"],
                    employment_type=v["employment_type"],
                    description=v["description"],
                    key_skills=",".join(v["key_skills"]),
                    employer_id=v["employer_id"],
                )
            )

        await session.commit()

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed())
